export interface MedicationReminder {
  id: string;
  name: string;
  dosage: string;
  timings: string; // General frequency description, e.g., "Once a day", "Twice a day"

  // New fields from the detailed form
  dosageForm?: 'tablet' | 'capsule' | 'syrup' | 'injection' | 'ointment' | 'drops' | 'patch' | 'inhaler' | 'other';
  specificTimes?: string[]; // Array of HH:mm strings e.g., ["08:00", "20:00"]
  startDate?: string; // ISO string for date, e.g., "2024-07-28"
  durationValue?: number;
  durationUnit?: 'days' | 'weeks' | 'months' | 'no_end_date';
  instructions?: string;
  refillReminderEnabled?: boolean;
  refillDaysBeforeEmpty?: number;
  medicationShape?: 'round' | 'oval' | 'oblong' | 'square' | 'diamond' | 'triangle' | 'other';

  isGenerated?: boolean; // True if generated by AI
  nextNotificationTime?: Date; // For scheduling notifications
}

export interface Visit {
  id: string;
  date: string; // ISO string e.g. "2024-07-28"
  doctorName: string;
  notes: string; // Corresponds to Clinical Notes / Observations
  specialization?: string;
  reasonForVisit?: string;
  nextAppointmentTime?: string; // HH:mm
  nextAppointmentNote?: string;
  attachedDocuments?: File[]; // Array of File objects
}

export interface MedicalDocument {
  id:string;
  name: string;
  type: 'prescription' | 'lab_report' | 'other';
  file: File | null; // Store the actual file object for upload
  filePreview?: string; // For image previews (data URL)
  uploadedAt: string; // ISO string
  visitId?: string; // Optional link to a visit
}

export type FacilityType =
  | "Government Hospital"
  | "PHC"
  | "Private Hospital"
  | "Jan Aushadhi Kendra"
  | "Diagnostic Lab"
  | "Pharmacy"
  | "Clinic";

export interface Facility {
  id: string;
  name: string;
  type: FacilityType;
  address: string;
  lat: number;
  lng: number;
  phone?: string;
  email?: string;
  website?: string;
  services?: string[];
  distance?: number;
}
