
export interface MedicationReminder {
  id: string;
  name: string;
  dosage: string;
  timings: string; // Example: "Twice a day at 8 AM and 8 PM"
  isGenerated?: boolean; // True if generated by AI
  nextNotificationTime?: Date; // For scheduling notifications
}

export interface Visit {
  id: string;
  date: string; // ISO string e.g. "2024-07-28"
  doctorName: string;
  notes: string;
}

export interface MedicalDocument {
  id:string;
  name: string;
  type: 'prescription' | 'lab_report' | 'other';
  file: File | null; // Store the actual file object for upload
  filePreview?: string; // For image previews (data URL)
  uploadedAt: string; // ISO string
  visitId?: string; // Optional link to a visit
}
